name: cograph
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - armadillo=14.6.3=h7dbe251_0
  - arpack=3.9.1=nompi_hf03ea27_102
  - fastspar=1.0.0=h1b620e3_6
  - gsl=2.7=he838d99_0
  - libblas=3.11.0=3_h4a7cf45_openblas
  - libcblas=3.11.0=3_h0358290_openblas
  - libgcc=15.2.0=he0feb66_14
  - libgcc-ng=15.2.0=h69a702a_14
  - libgfortran=15.2.0=h69a702a_14
  - libgfortran-ng=15.2.0=h69a702a_14
  - libgfortran5=15.2.0=h68bc16d_14
  - liblapack=3.11.0=3_h47877c9_openblas
  - libopenblas=0.3.30=openmp_hd680484_4
  - libstdcxx=15.2.0=h934c35e_14
  - llvm-openmp=21.1.7=h4922eb0_0
  - openblas=0.3.30=openmp_hd77311e_4
  - superlu=5.2.2=h00795ac_0
prefix: /home/sandra/miniconda3/envs/cograph
